#端口
server:
  port: 8083
 #context-path: /openconfig
  connection-timeout: 5000
  tomcat:
    uri-encoding: UTF-8
    #允许最大线程数
    max-threads: 2000
    #最大排队数
    accept-count: 1000
    min-spare-threads: 200
    max-connections: 5000
    
    accesslog:
      enabled: true
      #文件格式 %t %a "%r" %s (%D ms)
      pattern: pattern=remote_ip=%a local_ip=%A bytes=%b Bytes=%B  protocol=%H method=%m port=%p  url=%r code=%s sessionid=%S date=%t  millis=%D threadid=%I
      #前缀
      prefix: access_log
      rename-on-rotate: true
      request-attributes-enabled: false
      #日志切换
      rotate: true
      #缓冲输出 定期刷新
      buffered: true
      suffix: .log
      directory: /app/logs/tomcat

#mysql jdbc
spring:
  datasource:
    name: authDev
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.135.155:3307/open_dev
    username: dev_open
    password: 1qaz@WSX
  #springBoot开启热部署
  #devtools:
  #  restart:
  #  #热部署生效
  #    enabled: true
  #    #设置重启的目录
  #    additional-paths: src/main/java
  #    #classpath目录下的WEB-INF文件夹内容修改不重启
  #    exclude: WEB-INF/**
  resources:
    chain:
      # 关闭缓存
      cache: false
  thymeleaf:
    # 关闭 thymeleaf 缓存
    cache: false


logging:
  #加载日志文件
  config: classpath:config/logback/logback-springboot.xml
  #控制台打印sql语句
  level:
    root: info
    
#文件上传的路径配置
imgUploadConfig:
  product-image-file: /fileUpLoad/product_img
  partner-image-file: /fileUpLoad/partner_img
  img-pattern: image/jpeg,image/png