
#端口 
#mysql jdbc

server:
  tomcat: 
    uri-encoding: UTF-8
    max-threads: 10 
    min-spare-threads: 10
  connection-timeout: 5000

fileUploadConfig:
  windows-file-upload-path: "D://fileUpload//img//"
  linux-file-upload-path: "/fileUpLoad/img/"
  product-image-file: "product_img"
  partner-image-file: "partner_img"




spring:
  profiles:
    active: dev
  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    use-global-data-source-stat: true
  jackson:  
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

    
#监控范围
#      aop-patterns: com.yaic.auth.*
#      stat-view-servlet:
#        login-username: admin
#        login-password: 123
        

#mybatis加载
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yaic.auth.*.model
  #下划线转驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    
    
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

  
