#端口
server:
  port: 8083

  
#mysql jdbc
spring:
  datasource:
    name: authDev
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.135.155:3307/open_dev
    username: dev_open
    password: 1qaz@WSX

    

logging:
  #加载日志文件
  config: classpath:logback-springboot-dev.xml
  #控制台打印sql语句
  level:
    #com.yaic.auth.thirdparty.dao: debug
    #com.yaic.auth.interior.dao: debug


